### ISSUE TITLE
20.09 checklist

### ISSUE THREAD

**Issue by bruggerk** [usegalaxy-no/galaxyadmin#14]
### Looks and auth
- [x] Use the API to check that you now have the correct and expected version  https://<galaxy_root_URL>/api/version (@bruggerk, @torfinnnome)
- [x] Check that the styling is correct and looks like this example (example to be updated?) (@bruggerk, @kjellp )
- [ ] Check that login works with FEIDE (@kjellp)
- [x] Check that login works with NeLS IdP (@bruggerk, @kjetilkl )
- [ ] Only possible to logging through the NeLS portal (@bruggerk) The NeLS OIDC lets you select between NeLS and FEIDE now
- [x] Check that logout works correctly and that you have to re-enter your password to log in again. (@bruggerk, @kjetilkl )

### Links 
- [x] Check that the Help menu includes a link to "Support" and that this link takes you to the help desk web page at https://elixir.no/helpdesk (@bruggerk, @kjellp)
- [x] Check that the Help menu includes a link to "Terms & conditions" and that this link brings up the terms of service document in the middle panel (@bruggerk, @kjellp) Comment: appears in a second tab instead of middle panel
- [ ] ~~Check that the “Galaxy Support” link in the Help menu takes you to https://galaxyproject.org/support~~

### basic operations
- [x] Import a file from your local computer into your history (@bruggerk, @kjetilkl )
- [ ] Import a single file from the NeLS Storage (and display it!) (**Fails:** see issue #15 )(tested using prod nels, @bruggerk:)
- [ ] Import multiple files from the NeLS Storage in a single operation (and display them!)(tested using prod nels, @bruggerk:)
- [ ] Export one or more files to the NeLS Storage(tested using prod nels, @bruggerk:)
- [ ] Test a history export to Galaxy to NeLS (using prod nels, @bruggerk)
- [ ] Test a history import from NeLS to Galaxy (using prod nels, @bruggerk) 
- [x] Run a tool that comes bundled with Galaxy (e.g. "replace text") (@kjetilkl : Tested Grep1 and Sort1, @kjellp: Cut)
- [x] Run a tool that was installed from a tool shed (@bruggerk: bwa-mem, @torfinnnome: porechop)
- [x] Run a tool that uses a reference dataset (@bruggerk: bwa-mem, @torfinnnome: bowtie2)
- [x] Test a workflow (@bruggerk, @torfinnnome)
- [x] Test a Visualization plugin (@kjetilkl: Tested NGL viewer, PV protein viewer, Phyloviz, Cytoscape, Multiple Sequence Alignment, RNA Structure viewer, Scatterplot, Bar plot, Pie Chart and Heatmap. Added test data to shared Data Library, @torfinnnome)
- [ ] Test Trackster visualization (@kjetilkl: **Fails** due to missing CVMFS)
- [x] Test a Display Application (if configured), e.g. “UCSC Genome Browser” (@kjetilkl : tested with IGB and UCSC genome browser, @torfinnnome: UCSC)

### New stuff v20.09
- [x] Allow uploading directly from the tool form (@torfinnnome, @kjetilkl)
- [x] Workflow import from GA4GH TRS servers (@bruggerk, @torfinnnome)
- [x] [New datatypes](https://docs.galaxyproject.org/en/master/releases/20.09_announce_user.html#new-datatypes) (@kjetilkl : uploaded MP4 file and visualized it with "Video player", @torfinnnome)

### New stuff v20.01

- [x] workflow documentation. When it has finished, select “Workflow Invocations” from the “User” menu. Choose a workflow invocation and press the   V  -button to expand it. Press the “View Invocation Report” link below the two colored bars (not the printer icon!). (@bruggerk, @torfinnnome)

**Comment by kjetilkl** [comment]
Regarding the first item under "New stuff v20.09": 

Galaxy Europe has an additional "Upload Dataset" button in front of the "Browse Datasets" button behind the input dataset field in the tool form. Galaxy Main does not have this button, which has to be explicitly enabled by setting "upload_from_form_button" to "always on" in [galaxy.yml](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample)

**Comment by torfinnnome** [comment]
@kjetilkl Cool! We need that. I will fix.
