### ISSUE TITLE
Upgrade to 21.01 checklist

### ISSUE THREAD

**Issue by kjetilkl** [usegalaxy-no/galaxyadmin#42]
## Release notes
- [https://docs.galaxyproject.org/en/master/releases/21.01_announce.html](https://docs.galaxyproject.org/en/master/releases/21.01_announce.html)
- [https://docs.galaxyproject.org/en/master/releases/21.01_announce_user.html](https://docs.galaxyproject.org/en/master/releases/21.01_announce_user.html)

## Testing checklist
When you have performed a test, sign your name behind it. An item should only be checked off the list after a sufficient number of people have tested the same feature. Remember to use the [test server](https://test.usegalaxy.no) for now! The production server will be updated later.

### Looks and auth
- [x] Use the API to check that you now have the correct and expected version [https://(test.)usegalaxy.no/api/version](https://test.usegalaxy.no/api/version)   (@torfinnnome, @kjetilkl)
- [x] Check that the NeLS styling is correct (colors, logo, etc.) (@kjetilkl: mostly OK)
- [x] Check that login works with FEIDE (@kjellp, @kjetilkl)
- [ ] Check that login works with NeLS IdP (@kjellp, @kjetilkl )
- [x] :worried: Check that logout works correctly and that you have to re-enter your password to log in again. (@kjellp: not working for me, NeLS IdP login and Feide. @kjetilkl: mostly works but sometimes fails)

### Links 
- [x] Check that the Help menu includes a link to "Support" and that this link takes you to the help desk web page at https://elixir.no/helpdesk (@kjetilkl, @torfinnnome)
- [x] Check that the Help menu includes a link to "Terms & conditions" and that this link brings up the terms of service document in the middle panel (@kjetilkl, @torfinnnome)

### Basic operations
- [x] Import a file from your local computer into your history (@kjetilkl, @torfinnnome)
- [x] :worried: Import a single file from the NeLS Storage and display it! (@kjellp, @kjetilkl: it worked the second time I tried, but the first time I had to login again after being redirected back to Galaxy)
- [x] :worried: Import multiple files from the NeLS Storage in a single operation and display them! (@kjetilkl: it worked the second time I tried, but the first time I had to login again after being redirected back to Galaxy)
- [x] Export one or more files to the NeLS Storage (@kjellp, @kjetilkl)
- [x] :triangular_flag_on_post: Test a history export from Galaxy to NeLS (@kjetilkl: Fails with "disk space error")
- [x] Test a history import from NeLS to Galaxy (@torfinnnome, @kjetilkl)
- [x] Run a tool that comes bundled with Galaxy (e.g. "replace text") (@kjellp: "Select first", @kjetilkl: addValue, Cut1)
- [x] Run a tool that was installed from a tool shed (@kjetilkl: "Replace [parts of text]")
- [x] Run a tool that uses a reference dataset (e.g. bwa-mem) (@torfinnnome [C.elegans, ce10])
- [x] Test a workflow (@kjellp: "small text manip wf", @kjetilkl)
- [x] Test a Visualization plugin (if configured), e.g. “Charts” (@kjetilkl: Heatmap and Scatterplot)
- [x] Test Trackster visualization (@kjetilkl)
- [x] Test a Display Application (if configured), e.g. “UCSC Genome Browser” (@kjetilkl)

### New stuff v21.01
- [x] Workflow invocation details. After a workflow has been run, select “Workflow Invocations” from the “User” menu and click on the workflow name to show details (@kjellp, @kjetilkl)
- [x] Workflow author and license metadata annotations in the workflow editor (@kjetilkl)
- [x] Workflow "Best Practices". Lint a workflow by selecting "Best Practices" from the cogwheel menu in the workflow editor (@kjetilkl)
- [x] :triangular_flag_on_post: Workflow Reports (with visualizations!). Create a report template in the workflow editor and view the report after running the WF. (@kjetilkl: Works, but PDF version of the report fails. Probably requires a separate package installation)
- [x] See the disc usage for users on the Admin page (@kjetilkl)
- [x] Galaxy Training Materials button in the masthead (@kjetilkl, @kjellp )
- [x] :worried: Beta history panel (@torfinnnome, @kjetilkl: History menu webhooks, including NeLS history import/export, are not included in the Beta history panel)
- [x] Copy dataset link to clipboard (@kjetilkl: link works if user is logged in)
- [ ] File browser (Missing - not sure how to enable?)

### Additional history import/export tests
- [x] History import from another Galaxy server to UseGalaxy.no via link (@kjetilkl: imported history from Main)
- [ ] History export from UseGalaxy.no to another Galaxy server via link  (@kjetilkl: Exported history from prod and tried to import in Main, EU and test.usegalaxy.no, but all three failed. It worked from Main to EU)
- [x] History export to file (@kjetilkl)
- [x] History import from file (@kjetilkl)

**Comment by kjetilkl** [comment]
I just noticed that the gray backgrounds that are supposed to appear behind the selected tabs in the masthead are missing, and they have probably been missing for some time. (cf. [NTNU Galaxy](https://galaxy-ntnu.bioinfo.no/)) These were inspired by the look of the NeLS portal, but they are not critical in any way. Do we want them back?

**Comment by kjellp** [comment]
@kjetilkl I've not ,missed them, and see that usegalaxy.eu mostly do not have it either (except for Shared Data menu item, and that one works at usegalaxy.no also :) )

**Comment by torfinnnome** [comment]
> The "Beta History Panel" feature can be selected in the [history options menu](https://github.com/galaxyproject/galaxy/blob/dev/client/src/mvc/history/options-menu.js#L166), but we have [modified that file locally](https://github.com/usegalaxy-no/infrastructure-playbook/blob/master/env/common/files/galaxy/client/options-menu.js#L169) in order to fix history menu webhooks, which did not work properly before. Galaxy v21.01 now includes my [pull request](https://github.com/galaxyproject/galaxy/pull/10949) (Yay! my first contribution!), so we don't have to maintain our own file anymore. But it would be nice if we still replace the "Webhooks" label with "NeLS Storage" (line 194). It just makes more sense for the users.

Ok, have integrated v21.01 into options-menu.js on test now: https://github.com/usegalaxy-no/infrastructure-playbook/commit/5270fd9c0b05c53c3ec090d494b4b935d57f4712

PS: Woho, congratulations on your contribution. :-)

**Comment by torfinnnome** [comment]
I notice that we now have the FEIDE test credentials here. Is that ok? Now that all these issues are public (because of the wiki?)?

**Comment by kjellp** [comment]
Should probably be removed and only shared in more private channels like 
slack?

K.
