### ISSUE TITLE
Upgrade to 21.05 checklist

### ISSUE THREAD

**Issue by kjetilkl** [usegalaxy-no/galaxyadmin#47]
## Release notes
- [https://docs.galaxyproject.org/en/master/releases/21.05_announce.html](https://docs.galaxyproject.org/en/master/releases/21.05_announce.html)
- [https://docs.galaxyproject.org/en/master/releases/21.05_announce_user.html](https://docs.galaxyproject.org/en/master/releases/21.05_announce_user.html)

## Testing checklist
When you have performed a test, sign your name behind it. An item should only be checked off the list after a sufficient number of people have tested the same feature. Remember to use the [test server](https://test.usegalaxy.no) for now! The production server will be updated later.

### Updates to Galaxy configuration files

- [x] Check if any new Galaxy configuration files have been introduced and if there have been updates to existing configuration files, especially "galaxy.yml" and "datatypes_conf.xml" 
(@kjetilkl: Added two new configuration files to our playbook: "file_sources_conf.yml" and "user_preferences_extra_conf.yml", and set the paths for these in "galaxy.yml") 

### Updates to custom modified Galaxy files

- [x] The following three Galaxy code files (plus one style file) are replaced with our own custom modified copies in the playbooks. We must check if any of these have been updated since the previous Galaxy release, and if so, we should merge the new changes into our own copies. 
(@kjetilkl: updated "options-menu.js" and "psa_authnz.py" to v21.05. "Login.vue" has changed considerably, but I decided to keep our version as it was) 

* client/src/mvc/history/options-menu.js
* client/src/components/login/Login.vue
* lib/galaxy/authnz/psa_authnz.py
* client/src/style/scss/theme/blue.scss

### Looks and auth
- [x] Use the API to check that you now have the correct and expected version:  [https://(test.)usegalaxy.no/api/version](https://test.usegalaxy.no/api/version)
- [x] Check that the styling is correct and follows the NeLS theme 
- [x] Check that login works with FEIDE
- [x] Check that login works with NeLS IdP 
- [x] Check that logout works correctly and that you have to re-enter your password to log in again

### Links 
- [x] Check that the Help menu includes a link to "Support" and that this link takes you to the help desk web page at https://elixir.no/helpdesk 
- [x] Check that the Help menu includes a link to "Terms & conditions" and that this link brings up the terms of service document in the middle panel

### Basic operations
- [x] Import a file from your local computer into your history 
- [x] Import a single file from the NeLS Storage (and display it!)
- [x] Import multiple files from the NeLS Storage in a single operation (and display them!) 
- [x] Export one or more files to the NeLS Storage
- [x] Test a history export from Galaxy to NeLS 
- [x] Test a history import from NeLS to Galaxy 
- [x] Run a tool that comes bundled with Galaxy
- [x] Run a tool that was installed from a tool shed
- [x] Run a tool that uses a reference dataset (e.g. bwa-mem)
- [x] Test a workflow (@kjetilkl, @torfinnnome)
- [x] Test a Visualization plugin (if configured), e.g. “Charts”
- [x] Test Trackster visualization 
- [x] Test a Display Application (if configured), e.g. “UCSC Genome Browser”
- [x] History import from another Galaxy server to UseGalaxy.no via link
- [ ] History export from UseGalaxy.no to another Galaxy server via link  (Not working, but unrelated to upgrade)
- [x] History import from file
- [x] History export to file

### New stuff v20.01
- [x] workflow documentation. When it has finished, select “Workflow Invocations” from the “User” menu. Choose a workflow invocation and press the V-button to expand it. Press the “View Invocation Report” link below the two colored bars (not the printer icon!).

### New stuff v20.09
- [x] Allow uploading directly from the tool form 
- [x] Workflow import from GA4GH TRS servers

### New stuff v21.01
- [x] Workflow invocation details. After a workflow has been run, select “Workflow Invocations” from the “User” menu and click on the workflow name to show details. 
- [x] Workflow author and license metadata annotations in the workflow editor
- [x] Workflow "Best Practices". Lint a workflow by selecting "Best Practices" from the cogwheel menu in the workflow editor
- [x] Workflow Reports (with visualizations!). Create a report template in the workflow editor and view the report after running the WF.
- [x] See the disc usage for users on the Admin page
- [x] Galaxy Training Materials button in the masthead
- [x] Beta history panel

### New stuff v21.05
- [x] Import a file from a configured FTP server
- [x] Import a file from a configured S3FS server
- [x] Configure personal DropBox account under User => Preferences => Manage information
- [x] Import a file from your personal DropBox account
- [x] Export a history to your personal DropBox account
- [x] Import a history from your personal DropBox account

**Comment by kjetilkl** [comment]
Some observations regarding the failed tests:

In order to import a history via a URL from another Galaxy server, the history has to be "made accessible" by selecting "Share or Publish" from the history context menu, or else you will get a "HTTP 403 Forbidden" error when trying to import.

The "Export a history to your personal DropBox account" failed with the following error:
```
Traceback (most recent call last):
  File "/data/part0/tmp/jobs/000/829/configs/tmp0hguwxtz", line 1, in <module>
    from galaxy.tools.imp_exp.export_history import main; main()
  File "/srv/galaxy/server/lib/galaxy/tools/__init__.py", line 195
    min_version: Union[packaging.version.LegacyVersion, packaging.version.Version]
               ^
SyntaxError: invalid syntax
```
My hypothesis is that this could be a problem with the Python version.
It fails when the export job is executed on the (test) Slurm node, but it worked when I forced the job to run on the "local" node by adding the following line to the `/srv/galaxy/dynamic_rules/usegalaxy/tool_destinations.yaml` configuration file.
```
__EXPORT_HISTORY_TO_URI__: { runner: local }
```

**Comment by kjetilkl** [comment]
Regarding histories exported from UseGalaxy.no via URLs, these cannot be imported directly into other Galaxies using the link. The reason seems to be that UseGalaxy.no will redirect any client that does not have a valid Galaxy session to the login page. This also affects the current production server, so the problem is not related to the version upgrade. However, it only affects our server but works perfectly fine on EU and Main.
