### ISSUE TITLE
Upgrade to 21.09 checklist

### ISSUE THREAD

**Issue by kjetilkl** [usegalaxy-no/galaxyadmin#63]
## Release notes
- [https://docs.galaxyproject.org/en/master/releases/21.09_announce.html](https://docs.galaxyproject.org/en/master/releases/21.09_announce.html)
- [https://docs.galaxyproject.org/en/master/releases/21.09_announce_user.html](https://docs.galaxyproject.org/en/master/releases/21.09_announce_user.html)

## Testing checklist
When you have performed a test, sign your name behind it. An item should only be checked off the list after a sufficient number of people have tested the same feature. Remember to use the [test server](https://test.usegalaxy.no) for now! The production server will be updated later.

### Updates to Galaxy configuration files

- [x] Check if any new Galaxy configuration files have been introduced and if there have been updates to existing configuration files, especially "galaxy.yml" and "datatypes_conf.xml" 

@kjetilkl: I added a new "cache_dir" setting (introduced in v21.05) to "galaxy.yml". This was necessary to allow Galaxy to create a new cache-directory for bio.tools-related functionality. The setting "containers_resolvers_config_file" has been renamed to "container_resolvers_config_file". I also made a few updates to "tool_conf.xml".

### Updates to custom modified Galaxy files

- [x] The following three Galaxy code files (plus one style file) are replaced with our own custom modified copies in the playbooks. We must check if any of these have been updated since the previous Galaxy release, and if so, we should merge the new changes into our own copies. 

* client/src/mvc/history/options-menu.js
* client/src/components/login/Login.vue
* lib/galaxy/authnz/psa_authnz.py
* client/src/style/scss/theme/blue.scss

@kjetilkl: I updated "options-menu.js", "psa_authnz.py" and "Login.vue" to v21.09. The "Login.vue" file was then modified to give our login page a new look. Minor changes had been made to "blue.scss" but this was not updated.

### Looks and auth
- [ ] Use the API ([https://test.usegalaxy.no/api/version](https://test.usegalaxy.no/api/version)) to check that the server has the correct version, i.e. 21.09  (@kjetilkl, @tothuhien )
- [ ] Check that the styling is correct (still looks like the production server)  (@kjetilkl, @tothuhien )
- [ ] New login page  (@kjetilkl, @tothuhien )
- [ ] Check that login works with FEIDE   (@kjetilkl, @tothuhien I can not log in with FEIDE)
- [ ] Check that login works with NeLS IdP  (@kjetilkl, @tothuhien )
- [ ] Check that logout works correctly and that you have to re-enter your password to log in again.  (@kjetilkl: when I click the "Feide or NeLS ID" login button it remembers my previous choice and logs me in directly, @tothuhien : the same to me)

### Links 
- [ ] Check that the Help menu includes a link to "Support" and that this link takes you to the help desk web page at https://elixir.no/helpdesk (@tothuhien , @kjetilkl)
- [ ] Check that the Help menu includes a link to "Terms & conditions" and that this link brings up the terms of service document in the middle panel (@tothuhien : it brings me to a galaxy-terms page, but I don't see this in the middle panel, @kjetilkl: same here, and also same on UseGalaxy.org/eu, so I think they have changed where it is displayed)
- [ ] ~~Check that the “Galaxy Support” link in the Help menu takes you to https://galaxyproject.org/support~~

### Basic operations
- [ ] Import a file from your local computer into your history (@kjetilkl, @tothuhien )
- [ ] Import a single file from the NeLS Storage (and display it!)  (@kjetilkl, @tothuhien )
- [ ] Import multiple files from the NeLS Storage in a single operation (and display them!) (@kjetilkl: Sometimes the session is invalidated when returning back from the NeLS Storage, @tothuhien )
- [ ] Export one or more files to the NeLS Storage (@kjetilkl: **Not working**? Two hidden parameters, "File Path on NELS" and "NELS Id" should have been filled out automatically based on values returned from NeLS Storage, but they are not, @tothuhien: the same, it works when fills "File Path on Nels" and "Nels id" correctly & manually, those 2 parameters are not filled automatically)
- [ ] Test a history export from Galaxy to NeLS Storage (@kjetilkl, @tothuhien )
- [ ] Test a history import from NeLS Storage to Galaxy (@kjetilkl, @tothuhien )
- [ ] Run a tool that comes bundled with Galaxy (these are tools that do not refer to a toolshed in their tool IDs) (@kjetilkl, @tothuhien)
- [ ] Run a tool that was installed from a tool shed (@kjetilkl, @tothuhien )
- [ ] Run a tool that uses a reference dataset (e.g. bwa-mem) (@kjetilkl: Note that the resources available on the test compute nodes are too limited for many of the tools in the current configuration, @tothuhien )
- [ ] Test a workflow (@kjetilkl)
- [ ] Test a Visualization plugin (if configured), e.g. “Charts” (@kjetilkl, @tothuhien )
- [ ] Test Trackster visualization (@kjetilkl: ERROR: missing "bedtools" and "bedGraphToBigWig" on test server, @tothuhien same error)
- [ ] Test a Display Application (if configured), e.g. “UCSC Genome Browser”  (@kjetilkl: UCSC was redirected to login page when trying to fetch data, but it seemed to work with IGB)
- [ ]  History import from another Galaxy server to UseGalaxy.no via link  (@kjetilkl )
- [ ]  ~~History export from UseGalaxy.no to another Galaxy server via link~~   (this currently does not work)
- [ ]  History import from file (@kjetilkl, @tothuhien ) 
- [ ]  History export to file (@kjetilkl, @tothuhien )
- [ ]  Test the "bug report" function and verify that the email is sent to a sensible recipient (usegalaxy@usegalaxy.no) (@kjetilkl: the report email was sent to "usegalaxy@usegalaxy.no" and "kjetil.klepper@ntnu.no") 
- [ ]  Run a Data Manager (admin page) (@kjetilkl: ran BWA MEM indexer)

### New stuff v20.01
- [ ] workflow documentation. When it has finished, select “Workflow Invocations” from the “User” menu. Choose a workflow invocation and press the down arrow on the left to expand it. Press the “View Report” link above the two colored bars (not the printer icon!). (@kjetilkl)

### New stuff v20.09
- [ ] Allow uploading directly from the tool form  (@kjetilkl, @tothuhien )
- [ ] Workflow import from GA4GH TRS servers  (@kjetilkl: it works, but searches don't get many hits)

### New stuff v21.01
- [ ] Workflow invocation details. After a workflow has been run, select “Workflow Invocations” from the “User” menu and click on the workflow name to show details.  (@kjetilkl)
- [ ] Workflow author and license metadata annotations in the workflow editor  (@kjetilkl)
- [ ] Workflow "Best Practices". Lint a workflow by selecting "Best Practices" from the cogwheel menu in the workflow editor  (@kjetilkl) 
- [ ] Workflow Reports (with visualizations!). Create a report template in the workflow editor and view the report after running the WF.  (@kjetilkl)
- [ ] See the disc usage for users on the Admin page  (@kjetilkl)
- [ ] Galaxy Training Materials button in the masthead  (@kjetilkl)
- [ ] Beta history panel  (@kjetilkl)

### New stuff v21.05
- [ ] Pluggable Data Sources:
  - [ ] Import a file from a configured FTP server (@kjetilkl, @tothuhien )
  - [ ] Import a file from your personal DropBox account (configure it first under User => Preferences => Manage information) (@kjetilkl)
  - [ ] Export a file to your personal DropBox account using the "__Export datasets__ to remote files source" tool under Send Data (@kjetilkl: it works, but I am not able to select image files for some reason)
  - [ ] Export a history to your personal DropBox account (@kjetilkl)
  - [ ] Import a history from your personal DropBox account (@kjetilkl)
  - [ ] Import a file from a configured SSH server (configure it first under User => Preferences => Manage information) (@kjetilkl, @tothuhien : have error 'Problem listing file source path FileSourcePath(file_source=, path='/')')
  - [ ] Export a file to a configured SSH server using the "__Export datasets__ to remote files source" tool under Send Data (@kjetilkl, @tothuhien : have the same error as in the previous point 'Problem listing file source path FileSourcePath(file_source=, path='/')')

### New stuff v21.09
- [ ] Tool Panel Views  (@kjetilkl: if you select an EDAM-based view and then go back again to "Full Tool Panel", the mouse-over tool tips for the different categories are wrong. The same behaviour is found on other Galaxies, @tothuhien same here, and it keeps the EDAM-based view by default when I open a new session or refresh the page)
- [ ] News webhook (bell icon in masthead menu) (@kjetilkl, @tothuhien )

### NeLS Storage plugin
- [ ] Import personal files from NeLS Storage with the "Upload Data" tool ("Choose remote files" and then "NeLS Storage") (@kjetilkl, @tothuhien )
- [ ] Import project files from NeLS Storage with the "Upload Data" tool ("Choose remote files" and then "NeLS Storage Projects")
- [ ] Export files to NeLS Storage using the "__Export datasets__ to remote files source" tool under Send Data (@kjetilkl, @tothuhien )
- [ ] Import history from NeLS Storage (remote file) by clicking on "Import history" on the user's Saved Histories page (@kjetilkl, @tothuhien )
- [ ] Export history to NeLS Storage (remote file) by selecting "Export History to File" from the history options menu (cogwheel button in history panel) (@kjetilkl, @tothuhien )
